- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: "Include AWS role"
      include_role:
        name: "create_sg"
    - name: "Include AWS role"
      include_role:
        name: "create_instance"
