---
- name: Provision a set of instances
  ec2:
    region: "{{ aws_region }}"
    key_name: "{{ aws_key }}"
    group: "{{ security_group }}"
    instance_type: t2.micro
    image: "{{ ami_id }}"
    wait: true
    count: "{{ count }}"
    instance_tags:
      Name: Demo
  register: ec2

